# Generated by Django 4.1.1 on 2022-09-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='filter_code',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='filter_tag',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
